name: Build Textbook

on:
    push:
        branches: ["master", "main"]
    pull_request:
        branches: ["master", "main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run makedist.sh in Docker container
              run: |
                  cd ./ci
                  ./prepare-for-ci.sh
                  docker compose up -d
                  docker compose exec -T ibllinearalgebra ./makedist.sh
                  docker compose down

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: textbook
                  path: ci/dist/

            - name: Verifies all PDFs were built
              run: |
                  cd ./ci
                  ./verify-all-compiled.sh

    pretext_conversion:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: Run prepare-for-pretext-conversion.sh
              run: |
                  cd ./ci
                  ./prepare-for-pretext-conversion.sh

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: textbook-pretext
                  path: ci/book-pretext/pretext-output
