name: Build Textbook

on:
    push:
        branches: ["master", "main"]
    pull_request:
        branches: ["master", "main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run makedist.sh in Docker container
      run: |
        cd ./ci
        ./prepare-for-ci.sh
        docker compose up -d
        docker compose exec -T ibllinearalgebra ./makedist.sh
        docker compose down

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: textbook
        path: ci/dist/